micronaut:
  application:
    name: micronaut-demo
  server:
    port: 8080

datasources:
  default:
    url: jdbc:mysql://74.208.33.72:63306/xpress_dinero?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: xpress_dinero_noco
    password: x&p20q6H2
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 